# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsa_cipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtPlaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPlaintext.setGeometry(QtCore.QRect(73, 140, 241, 71))
        self.txtPlaintext.setObjectName("txtPlaintext")
        self.txtCiphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtCiphertext.setGeometry(QtCore.QRect(70, 280, 241, 71))
        self.txtCiphertext.setObjectName("txtCiphertext")
        self.txtInformation = QtWidgets.QTextEdit(self.centralwidget)
        self.txtInformation.setGeometry(QtCore.QRect(520, 140, 261, 71))
        self.txtInformation.setObjectName("txtInformation")
        self.txtSignature = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSignature.setGeometry(QtCore.QRect(520, 280, 261, 71))
        self.txtSignature.setObjectName("txtSignature")
        self.RSACipher = QtWidgets.QLabel(self.centralwidget)
        self.RSACipher.setGeometry(QtCore.QRect(286, 50, 91, 20))
        self.RSACipher.setObjectName("RSACipher")
        self.Plaintext = QtWidgets.QLabel(self.centralwidget)
        self.Plaintext.setGeometry(QtCore.QRect(10, 140, 47, 13))
        self.Plaintext.setObjectName("Plaintext")
        self.Ciphertext = QtWidgets.QLabel(self.centralwidget)
        self.Ciphertext.setGeometry(QtCore.QRect(10, 280, 61, 16))
        self.Ciphertext.setObjectName("Ciphertext")
        self.Signature = QtWidgets.QLabel(self.centralwidget)
        self.Signature.setGeometry(QtCore.QRect(440, 280, 47, 13))
        self.Signature.setObjectName("Signature")
        self.Information = QtWidgets.QLabel(self.centralwidget)
        self.Information.setGeometry(QtCore.QRect(440, 140, 61, 16))
        self.Information.setObjectName("Information")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(80, 420, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(220, 420, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.btnSign = QtWidgets.QPushButton(self.centralwidget)
        self.btnSign.setGeometry(QtCore.QRect(530, 420, 75, 23))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setGeometry(QtCore.QRect(680, 420, 75, 23))
        self.btnVerify.setObjectName("btnVerify")
        self.btnGenerateKey = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerateKey.setGeometry(QtCore.QRect(420, 50, 75, 23))
        self.btnGenerateKey.setObjectName("btnGenerateKey")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RSACipher.setText(_translate("MainWindow", "RSA CIPHER"))
        self.Plaintext.setText(_translate("MainWindow", "Plain Text"))
        self.Ciphertext.setText(_translate("MainWindow", "Cipher Text"))
        self.Signature.setText(_translate("MainWindow", "Signature"))
        self.Information.setText(_translate("MainWindow", "Information"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btnSign.setText(_translate("MainWindow", "Sign"))
        self.btnVerify.setText(_translate("MainWindow", "Verify"))
        self.btnGenerateKey.setText(_translate("MainWindow", "Generate Key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
